### ISSUE TITLE
Error Initializing Using #getDefaultResourceInstance()

### ISSUE THREAD

**Issue by mrcritical** [extjwnl/extjwnl#1]
When using Dictionary.getDefaultResourceInstance() with extjwnl-data-wn31, the Maven dependency, I get the following exception:

```
Caused by: java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:492)
    at java.lang.Integer.parseInt(Integer.java:527)
    at net.sf.extjwnl.dictionary.Dictionary.<init>(Dictionary.java:371)
    at net.sf.extjwnl.dictionary.AbstractCachingDictionary.<init>(AbstractCachingDictionary.java:65)
    at net.sf.extjwnl.dictionary.FileBackedDictionary.<init>(FileBackedDictionary.java:57)
    ... 8 more
```

**Comment by hanito** [comment]
Hi I am still have the same problem:
java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at net.didion.jwnl.data.VerbFrame.initialize(VerbFrame.java:22)
        at net.didion.jwnl.JWNL.initialize(JWNL.java:145)
        at cuny.blender.kbp.nlp.semantics.ontologies.WordNet.initialize(WordNet.java:96)
        at cuny.blender.kbp.slotfilling.PASlotFilling.<init>(PASlotFilling.java:240)
        at cuny.blender.kbp.slotfilling.PASlotFilling.<init>(PASlotFilling.java:175)
        at cuny.blender.kbp.slotfilling.PASlotFilling.main(PASlotFilling.java:161)

And where Can i find this function?Dictionary.getResourceInstance("/net/sf/extjwnl/data/wordnet/wn31/res_properties.xml");

**Comment by autayeu** [comment]
```Dictionary.getResourceInstance``` is in ```Dictionary``` class. This error usually comes when you mix versions. Please, use latest versions and make sure you don't have old versions or configs in the classpath.
