### ISSUE TITLE
MySQLSyntaxErrorException -> SYNSET_WORD_SQL 

### ISSUE THREAD

**Issue by dayre** [extjwnl/extjwnl#14]
After loading the 3.0 data files into a mysql db, and running the Example.java, it barfs due to a syntax error in the SYNSET_WORD_SQL constant, there is a space missing before the "ORDER BY" on the 
previous line in the DatabaseManagerImpl.java.

`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BY sw.word_index' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at net.sf.extjwnl.dictionary.database.Query.execute(Query.java:35)
	at net.sf.extjwnl.dictionary.DatabaseBackedDictionary.getSynsetAt(DatabaseBackedDictionary.java:127)
`

**Comment by autayeu** [comment]
Thank you for reporting. I've added that space there. I think it can be closed now. But in case there are further issues with this, feel free to reopen.

**Comment by dayre** [comment]
Thank you for the quick fix !
