### ISSUE TITLE
Endless loop

### ISSUE THREAD

**Issue by Nickqwer** [extjwnl/extjwnl#17]
hi, my CPU has been under 100% for several days, I suspect an endless loop, this is the stacktrace causing the issue:
"taskExecutor-13" #649 prio=5 os_prio=0 tid=0x00007fb70041d800 nid=0x77e9 runnable [0x00007fb6f4dd5000]
   java.lang.Thread.State: RUNNABLE
        at net.sf.extjwnl.dictionary.file_manager.FileManagerImpl.getIndexedLine(FileManagerImpl.java:217)
        at net.sf.extjwnl.dictionary.FileBackedDictionary.getIndexWord(FileBackedDictionary.java:130)
        at net.sf.extjwnl.dictionary.morph.LookupIndexWordOperation.execute(LookupIndexWordOperation.java:22)
        at net.sf.extjwnl.dictionary.morph.AbstractDelegatingOperation.delegate(AbstractDelegatingOperation.java:54)
        at net.sf.extjwnl.dictionary.morph.TokenizerOperation.tryAllCombinations(TokenizerOperation.java:130)
        at net.sf.extjwnl.dictionary.morph.TokenizerOperation.tryAllCombinations(TokenizerOperation.java:101)
        at net.sf.extjwnl.dictionary.morph.TokenizerOperation.execute(TokenizerOperation.java:74)
        at net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor$LookupInfo.executeNextOperation(DefaultMorphologicalProcessor.java:177)
        at net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor.lookupAllBaseForms(DefaultMorphologicalProcessor.java:104)
        - locked <0x00000000fa0639b0> (a net.sf.extjwnl.dictionary.morph.DefaultMorphologicalProcessor$LookupInfo)

**Comment by autayeu** [comment]
If you would give more details, that might help.

For now I'd guess. One idea is that you might be facing combinatorial explosion in "tryAllCombinations". That happens if you try searching for something long, for example feed an entire sentence into search: it will try finding different combinations in the dictionary and there is just too many of those.

If you can give more details on this case, please, add the details and reopen. Thank you.
