### ISSUE TITLE
java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"

### ISSUE THREAD

**Issue by hanito** [extjwnl/extjwnl#7]
I have the following problem when I use JWNL1.3:

java.lang.NumberFormatException: For input string: "NUMBER_OF_VERB_FRAMES"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:492)
at java.lang.Integer.parseInt(Integer.java:527)
at net.didion.jwnl.data.VerbFrame.initialize(VerbFrame.java:22)
at net.didion.jwnl.JWNL.initialize(JWNL.java:145)
at cuny.blender.kbp.nlp.semantics.ontologies.WordNet.initialize(WordNet.java:96)
at cuny.blender.kbp.slotfilling.PASlotFilling.(PASlotFilling.java:240)
at cuny.blender.kbp.slotfilling.PASlotFilling.(PASlotFilling.java:175)
at cuny.blender.kbp.slotfilling.PASlotFilling.main(PASlotFilling.java:161)

And where Can i find this function?Dictionary.getResourceInstance("/net/sf/extjwnl/data/wordnet/wn31/res_properties.xml");

**Comment by autayeu** [comment]
```
when I use JWNL1.3
```
I'm sorry, this is a different project.
